version: 2
jobs:
  build:
    working_directory: /work
    docker:
      - image: node:14.4.0
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: test
          command: npm test
